version: '3.8'
services:

  database:
    image: mysql:latest
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm