controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login_device:
    path: /api/device
    controller: App\Controller\DeviceController::signIn
    methods: POST